version: "3.4"
services:
        dist_server:
                image: node:14
                working_dir: /app
                volumes:
                        - "./:/app"
                ports:
                        - "5000:5000"
                entrypoint: 
                        - "/bin/bash"
                        - "-c"
                        - "npm run dist"
